### ISSUE TITLE
Does not seem to work

### ISSUE THREAD

**Issue by stefastra** [MutlaqAldhbuiub/randomPrnt.sc#2]
![Screenshot_2](https://github.com/MutlaqAldhbuiub/randomPrnt.sc/assets/46135339/82b4f972-4a91-40bb-bc93-67d358bad1e7)

**Comment by MutlaqAldhbuiub** [comment]
Hello @stefastra 
It works fine!
You can access it through http://localhost:3000/ 
this project is for testing only
![screencapture-localhost-3000-2023-08-12-20_52_22](https://github.com/MutlaqAldhbuiub/randomPrnt.sc/assets/9112378/06aed7d8-fd22-46dc-9fab-3307e572dee0)
